# Generated by Django 5.1 on 2025-04-29 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='delivery_method',
            field=models.CharField(choices=[('cargus', 'Cargus'), ('sameday', 'Sameday'), ('pickup', 'Ridicare personală')], default='cargus', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
