# Generated by Django 5.0.6 on 2024-07-02 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_cartitem_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
